### PR TITLE
Set nibabel version

### PR DESCRIPTION
**Pull request by brudfors**
It seems as `nitorch.io` errors when using the latest version of nibabel as its backend:
```py
AttributeError: type object 'ArrayProxy' has no attribute 'order'
```
Setting the nibabel version that nitorch uses to an older one seems to fix the problem.

@balbasty, have I changed the nibabel version in all places needed?

### CODE REVIEW

**Comment by brudfors** [comment]
It works on v4.0.2, not more recent ones. Should I change to `nibabel<=4` then?

**Comment by balbasty** [comment]
Looks like they went straight from 4.0 to 5.0, so yeah `<= 4` would work, thanks!

**Comment by brudfors** [comment]
Great, @balbasty please merge if you think looks OK.
